### ISSUE TITLE
Fails on any partition other than "aws"

### ISSUE THREAD

**Issue by stensonb** [redbubble/yak#100]
This prevents submitting SAML assertions of roles which are from another partition...govcloud (https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-arns.html), for example.

Here's the error message:
```
$ AWS_REGION=us-gov-west-1 yak "arn:aws-us-gov:iam::123456789012:role/purple-clerical" aws sts get-caller-identity
'arn:aws-us-gov:iam::123456789012:role/purple-clerical' is neither an IAM role ARN nor a configured alias.

Run 'yak --list-roles' to see which roles and aliases you can use.
$
```

**Comment by stensonb** [comment]
Fixed by #101

**Comment by rbvigilante** [comment]
Sorry we haven't been paying attention to this - I think there are some notification settings we might need to tweak.

Very happy to apply this fix - we weren't aware there was already machinery available to verify ARNs when we made the check.

**Comment by stensonb** [comment]
No problem, happy to help!

**Comment by rbvigilante** [comment]
Thank you, we really appreciate it!
