### ISSUE TITLE
Completion breaks with `--`

### ISSUE THREAD

**Issue by toothbrush** [redbubble/yak#36]
To disambiguate flags from commands i sometimes have to do 

```sh
yak prod -- thing --flag
```

..but completion breaks after the `--`.

**Comment by toothbrush** [comment]
PS this is on zsh.

**Comment by rbvigilante** [comment]
So apparently by default, most commands expect the `--` to signify the _end of their `-/--` flags. So, the correct syntax should probably actually be `yak -- <role> <command --flag>`.

**Comment by toothbrush** [comment]
Alright, i can live with that.  Thanks for investigating!

On 2018-05-09 at 01:19 UTC+0000, quoth Michael Vigilante:
