### ISSUE TITLE
Installation instructions need a correction in order to work

### ISSUE THREAD

**Issue by TJC** [redbubble/yak#38]
This command, from the installation instructions, just writes to a file called "sudo" in the local directory.  
I think you wanted to use the `|` instead of `>`

`echo "deb http://apt.redbubble.com/ stable main" > sudo tee /etc/apt/sources.list.d/yak.list`

**Comment by toothbrush** [comment]
Yep, definitely.  I use a `sudo`-free approach of writing directly to the file, and so just blindly edited in `sudo tee`.  Thanks.
