### ISSUE TITLE
Accept Okta password via shell environment or parameter

### ISSUE THREAD

**Issue by TJC** [redbubble/yak#55]
```
# Examples
# Method 1 via shell:
~$ YAK_PASSWORD=$(~/bin/unwrap-yak-password) yak production

# Method 2 via parameter:
~$ yak -p $(~/bin/unwrap-yak-password) production
```

**Comment by toothbrush** [comment]
I like this much more than the other suggestion, https://github.com/redbubble/yak/pull/49, because this gives the user a lot more freedom in how to implement it.

**Comment by rbvigilante** [comment]
I really don't like the parameter, because the obvious way to use it is `-p w00myp4ssw0rdissh0wing`. I could be convinced by the environment variable perhaps.

**Comment by TJC** [comment]
I'd prefer the environment method myself; slightly harder for an attacker to nab it.
ie. They need access to your account to grep your .bash_history or root to access `/proc/$pid/environ`

**Comment by TJC** [comment]
But if an attacker has access to your account, or to root, they don't even need to do that -- they can just put a hacked version of 'yak' in your path, which captures the password when you enter it and pings a webhook somewhere with it in plaintext, before continuing.

**Comment by toothbrush** [comment]
> I really don't like the parameter, because the obvious way to use it is -p w00myp4ssw0rdissh0wing. I could be convinced by the environment variable perhaps.

Yep, which will stick around in your `$SHELL` history. 

+1 for the environment variable thing, and indeed i'd use it precisely like @TJC's Method #1 shows.
