### ISSUE TITLE
Issue around credentials cache locking with multiple yak processes

### ISSUE THREAD

**Issue by TJC** [redbubble/yak#62]
# Bug description
I ended up in a situation where I had several scripts that were retrying calling yak to parse the output, but were all blocking on the MFA prompt - and then killing yak and retrying, repeatedly.

Meanwhile, I opened up a terminal prompt, ran yak, and entered my MFA token. yak ran successfully.

I expected the various scripts to now be able to run successfully -- but they were still hitting the MFA prompt. Indeed, when I ran yak again manually, it too asked for my MFA.

After killing the automated scripts and their attempts to run yak, I was able to run yak manually and have it cache my credentials. But it seems like something was preventing that from working while other instances were around.

**Comment by rbvigilante** [comment]
I'm not super surprised by this. We didn't really design `yak` with multiple processes in mind. That said, we should still look into fixing it!

**Comment by rbvigilante** [comment]
(I did not intend to close this issue, I pressed the wrong button)

**Comment by TJC** [comment]
I suspect the fix is: Only call `writeCache()` upon successful commands.

**Comment by rbvigilante** [comment]
So related to the fix for #44?

**Comment by rbvigilante** [comment]
Perhaps we could make a '--dont-write-cache' option, or check `$_` and not write the cache unless `yak` is being called interactively?

**Comment by TJC** [comment]
Why would you want to write to the cache, if you don't have any good news to update it with?

(I'm sure it's possible there are legitimate reasons. I do not fully understand what it does, apart from cache successful credentials)

**Comment by rbvigilante** [comment]
Oh right, you mean that if `yak` fails to authenticate at all it shouldn't write the cache. That's probably also a good idea!

**Comment by TJC** [comment]
Steps to reproduce:
- wipe your cache at start of test
- run yak, and let it sit at the MFA prompt
- run yak again in another window, and go through the MFA prompt correctly.
- run yak again in another window, observing that you are not prompted for anything (ie cached)
- go back to first yak and hit Ctrl-C to get out of it
- run yak again, observing that now you get another MFA prompt

**Comment by TJC** [comment]
I think the `--cache-only` option provides a work-around for my use-case, but I believe it's still a bug that yak will overwrite "good" cache details with "failed" cache details.
